const p=window.ACADEMIC_PROFILE;
const routes=['about','research','publications','networks','conferences','recognition','profiles','contact'];
const labels={en:{about:'About me',research:'Research',publications:'Publications',projects:'Projects',experience:'Research experience',conferences:'Conferences',recognition:'Recognition',contact:'Contact',education:'Education',awards:'Awards and Distinctions',connect:'Let’s Connect',invitation:'For collaborations, academic inquiries, or biodiversity research projects, please write to.',papers:'Journal articles',events:'Conferences and scientific meetings',eventsNote:'Scientific meetings and research presentations.',awardsNote:'Details of awards and distinctions will be added soon.',cv:'Academic CV',print:'Print / Save as PDF',back:'Back to profile',menu:'Menu',language:'Language',skip:'Skip to content'},es:{about:'Sobre mí',research:'Investigación',publications:'Publicaciones',projects:'Proyectos',experience:'Experiencia investigativa',conferences:'Conferencias',recognition:'Reconocimientos',contact:'Contacto',education:'Formación académica',awards:'Premios y distinciones',connect:'Conversemos',invitation:'Para colaboraciones, consultas académicas o proyectos de investigación sobre biodiversidad, puedes escribirme a:',papers:'Artículos científicos',events:'Conferencias y encuentros científicos',eventsNote:'Encuentros científicos y presentaciones de investigación.',awardsNote:'Próximamente se incorporarán los detalles de premios y distinciones.',cv:'CV académico',print:'Imprimir / Guardar como PDF',back:'Volver al perfil',menu:'Menú',language:'Idioma',skip:'Saltar al contenido'}};
let lang=new URLSearchParams(location.search).get('lang')==='es'?'es':'en';
let publicationPage=0;
const isCV=document.body.dataset.cv==='true';
const view=document.getElementById('view');
const txt=v=>typeof v==='object'&&v!==null?(v[lang]||v.en||''):(v||'');
const esc=v=>String(txt(v)).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=(url,title,cls='')=>`<a class="${cls}" href="${esc(url)}">${esc(title)}</a>`;
const L=()=>labels[lang];
function photo(route){const x=p.photos?.[route];return x?.src?`<figure class="work-photo"><img src="${esc(x.src)}" alt="${esc(x.alt)}" width="1400" height="440"><figcaption>${esc(x.caption)}</figcaption></figure>`:'';}
function education(){return `<h2 class="section-title">${L().education}</h2><div class="education-grid">${p.education.map(r=>`<article><h3>${esc(r.degree)}</h3><p>${esc(r.institution)}</p><p>${esc(r.period)}</p></article>`).join('')}</div>`;}
function about(){return `<p class="eyebrow">${L().about}</p><div class="hero-split"><div class="hero-intro"><p class="eyebrow">${lang==='en'?'EVOLUTION · BIODIVERSITY · ECOSYSTEM HEALTH':'EVOLUCIÓN · BIODIVERSIDAD · SALUD ECOSISTÉMICA'}</p><h1>Jordan Camilo<br>Hernández Martelo</h1><p class="hero-tagline">${esc(p.tagline)}</p><p class="role">${esc(p.role)}</p><div class="quick-links">${link('#publications',L().publications+' ↗','quick-link')}${link('#contact',L().contact+' ↗','quick-link secondary')}</div></div>${isCV?'':galleryMarkup(p.gallery,lang)}</div><div class="bio-panel"><div class="bio-symbol" aria-hidden="true">${icon('biology')}</div><div><p>${esc(p.bio)}</p><p>${esc(p.bioSecondary)}</p><p class="institution">${esc(p.affiliation)}</p></div></div>${education()}`;}
function research(){return `<h1>${L().research}</h1><p class="page-intro">${esc(p.introduction)}</p><div class="research-grid">${p.research.map(r=>`<article data-icon="${esc(r.icon)}"><h2>${esc(r.title)}</h2><p>${esc(r.description)}</p></article>`).join('')}</div>`;}
function publications(){const pubs=[...p.publications].sort((a,b)=>Number(b.year)-Number(a.year));const perPage=15,totalPages=Math.ceil(pubs.length/perPage),shown=isCV?pubs:pubs.slice(publicationPage*perPage,(publicationPage+1)*perPage);const pagination=!isCV&&totalPages>1?`<nav class="publication-pagination" aria-label="${lang==='en'?'Publication pages':'Páginas de publicaciones'}">${Array.from({length:totalPages},(_,i)=>`<button type="button" data-publication-page="${i}" ${i===publicationPage?'aria-current="page"':''}>${i+1}</button>`).join('')}</nav>`:'';return `<p class="eyebrow">${L().papers}</p><h1>${L().publications}</h1>${featuredPublications()}<h3 class="list-heading">${lang==='en'?'All publications':'Todas las publicaciones'}</h3><div id="publication-list">${shown.map(r=>`<article class="publication"><div class="pub-year">${esc(r.year)}</div><div><h2>${esc(r.title)}</h2><p>${esc(r.authors)}</p><p class="citation-line">${esc(r.venue)} · ${link(r.url,'DOI: '+r.url.replace('https://doi.org/',''),'doi')}</p></div></article>`).join('')}</div>${pagination}`;}
function groups(){return `<p class="eyebrow">${L().groups}</p><h1>${lang==='en'?'Research Networks':'Redes de investigación'}</h1><div class="network-grid">${p.groups.map(r=>`<article><h3>${esc(r.title)}</h3><p>${esc(r.institution)}</p></article>`).join('')}</div>`;}
function memberships(){return `<p class="eyebrow">${L().memberships}</p><h1>${lang==='en'?'Professional Memberships':'Membresías profesionales'}</h1><div class="network-grid">${p.memberships.map(r=>`<article><h3>${esc(r.title)}</h3></article>`).join('')}</div>`;}
function profiles(){return `<h1>${L().profiles}</h1><div class="network-grid">${p.links.map(r=>`<article><h3>${link(r.url,r.label+' ↗')}</h3></article>`).join('')}</div>`;}
function experience(){return `<h1>${L().experience}</h1>${p.experience.map(r=>`<article class="timeline-item"><p class="period">${esc(r.period)}</p><div><h3>${esc(r.role)}</h3><p class="institution">${esc(r.institution)}</p><p>${esc(r.description)}</p></div></article>`).join('')}`;}
function conferences(){return `<p class="eyebrow">${L().conferences}</p><h1>${L().events}</h1><p class="page-intro">${L().eventsNote}</p>${[...p.conferences].sort((a,b)=>b.date.localeCompare(a.date)).map(r=>`<article class="timeline-item"><p class="period">${esc(r.period)}</p><div><h3>${esc(r.title)}</h3><p>${esc(r.description)}</p></div></article>`).join('')}`;}
function recognition(){return `<p class="eyebrow">${L().recognition}</p><h1>${L().awards}</h1>${p.awards.length?[...p.awards].sort((a,b)=>Number(b.year)-Number(a.year)).map(r=>`<article class="timeline-item"><p>${esc(r.period || r.year || (lang==='en'?'Year to be confirmed':'Año por confirmar'))}</p><div><h3>${esc(r.title)}</h3><p>${esc(r.institution)}</p><p>${esc(r.description)}</p></div></article>`).join(''):`<p class="notice">${L().awardsNote}</p>`}`;}
function contact(){return `<p class="eyebrow">${L().contact}</p><div class="contact-panel"><h1>${L().connect}</h1><p>${L().invitation}</p>${p.emails.map(email=>link('mailto:'+email,email,'email')).join('')}</div>`;}

function featuredPublications(){if(isCV)return '';const selected=(p.featuredPublications||[]).map(url=>p.publications.find(r=>r.url===url)).filter(Boolean);return `<h3 class="list-heading">${lang==='en'?'Selected publications':'Publicaciones destacadas'}</h3><div class="featured-grid">${selected.map(r=>`<article data-icon="publications"><p class="eyebrow">${esc(r.year)}</p><h3>${esc(r.title)}</h3><p class="citation-line">${esc(r.venue)} · ${link(r.url,'DOI ↗','doi')}</p></article>`).join('')}</div>`;}
function networks(){return `<h1>${L().networks}</h1><p class="page-intro">${lang==='en'?'Research collaborations and scientific communities.':'Colaboraciones de investigación y comunidades científicas.'}</p><div class="network-subsection" id="groups"><h3>${L().groups}</h3><div class="network-grid">${p.groups.map(r=>`<article data-icon="groups"><h4>${esc(r.title)}</h4><p>${esc(r.institution)}</p></article>`).join('')}</div></div><div class="network-subsection" id="memberships"><h3>${L().memberships}</h3><div class="network-grid">${p.memberships.map(r=>`<article data-icon="memberships"><h4>${esc(r.title)}</h4></article>`).join('')}</div></div>`;}

const renderers={about,research,publications,networks,groups,memberships,profiles,experience,conferences,recognition,contact};

Object.assign(labels.en,{networks:'Academic networks',news:'News',groups:'Research groups',memberships:'Scientific associations',profiles:'Online profiles & media'});
Object.assign(labels.es,{networks:'Redes académicas',news:'Noticias',groups:'Grupos de investigación',memberships:'Asociaciones científicas',profiles:'Perfiles y medios'});
const iconPaths={about:'<circle cx="12" cy="7" r="4"/><path d="M4 22v-3a8 8 0 0 1 16 0v3"/>',research:'<path d="M9 3h6M10 3v7L4 20h16l-6-10V3M7 15h10"/>',publications:'<path d="M5 3h10l4 4v14H5zM14 3v5h5M8 12h8M8 16h8"/>',groups:'<circle cx="12" cy="5" r="3"/><circle cx="5" cy="18" r="3"/><circle cx="19" cy="18" r="3"/><path d="m10 8-4 7m8-7 4 7M8 18h8"/>',memberships:'<circle cx="9" cy="7" r="3"/><path d="M2 21v-3a7 7 0 0 1 14 0v3M17 4a3 3 0 0 1 0 6m2 4a6 6 0 0 1 3 5v2"/>',profiles:'<circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/>',experience:'<rect x="3" y="7" width="18" height="14" rx="2"/><path d="M8 7V3h8v4M3 13h18M10 13v3h4v-3"/>',conferences:'<rect x="3" y="4" width="18" height="12" rx="1"/><path d="M12 16v6m-5 0 5-6 5 6M7 9h10M7 12h6"/>',recognition:'<circle cx="12" cy="8" r="5"/><path d="m8 12-2 9 6-3 6 3-2-9"/>',contact:'<rect x="2" y="5" width="20" height="14" rx="2"/><path d="m2 6 10 8L22 6"/>'};
Object.assign(iconPaths,{
biology:'<path d="M4 20C4 10 8 4 20 3c1 10-4 17-12 15M4 20 16 8M8 16l-1-5m5 1 5 1"/><circle cx="7" cy="11" r="1.5" fill="#dfe7fb"/><circle cx="12" cy="12" r="1.5" fill="#dfe7fb"/><circle cx="16" cy="8" r="1.5" fill="#dfe7fb"/>',
invasion:'<ellipse cx="10" cy="13" rx="3" ry="5"/><path d="M8 8 6 5m6 3 2-3M7 11H3m4 4H2m5 2-3 3m9-9 3-2m-3 6 3 3M17 4h5v5m-5 0 5-5M10 9v9"/>',
news:'<rect x="3" y="3" width="18" height="18" rx="2"/><path d="M7 7h10M7 11h4v4H7zM14 11h3m-3 4h3M7 18h10"/>',
morphometrics:'<path d="m6 4 13 3-2 13L4 17Z M6 4l11 16M4 17 19 7"/><circle cx="6" cy="4" r="2" fill="white"/><circle cx="19" cy="7" r="2" fill="white"/><circle cx="17" cy="20" r="2" fill="white"/><circle cx="4" cy="17" r="2" fill="white"/>',
ecosystem:'<path d="M20 3C9 1 3 6 4 13c1 7 11 9 15 2 2-4 1-8 1-12ZM3 21l7-7M2 12h5l2-4 3 9 3-5h7"/>'
});
const icon=r=>`<span class="item-icon" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">${iconPaths[r]||iconPaths.research}</svg></span>`;
let active='about', scrollPending=false;
function routeFromHash(){const x=location.hash.slice(1);return routes.includes(x)?x:({'projects':'networks','proyectos':'networks','groups':'networks','memberships':'networks','inicio':'about','sobre-mi':'about','cv':'about','news':'profiles','noticias':'profiles'}[x]||'about');}
function activate(id){active=id;document.querySelectorAll('#navigation a').forEach(a=>{if(a.getAttribute('href')==='#'+id)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});}
function jump(id,smooth=true){const section=document.getElementById(id);if(!section)return;activate(id);const offset=innerWidth<=650?document.querySelector('header').getBoundingClientRect().height:nav.getBoundingClientRect().height;window.scrollTo({top:Math.max(0,scrollY+section.getBoundingClientRect().top-offset-24),behavior:'instant'});}
function decorate(){view.querySelectorAll('.page-section').forEach(section=>{const first=section.querySelector('h1');if(first&&section.id!=='about'){const h=document.createElement('h2');h.innerHTML=first.innerHTML;h.className='page-heading';first.replaceWith(h);}section.querySelectorAll('article').forEach(a=>a.insertAdjacentHTML('afterbegin',icon(a.dataset.icon||section.id)));});}
function initSectionObserver(){if(isCV)return ()=>{};const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add('section-visible');}),{threshold:.08,rootMargin:'0px 0px -8%'});view.querySelectorAll('.page-section').forEach(section=>observer.observe(section));return ()=>observer.disconnect();}
function render(){window.destroyGallery?.();window.destroySectionObserver?.();document.documentElement.lang=lang;document.getElementById('language').value=lang;document.querySelector('.language-label').textContent=L().language;document.querySelector('.skip').textContent=L().skip;document.getElementById('menu-toggle').textContent=L().menu;document.getElementById('year').textContent=new Date().getFullYear();document.getElementById('cv-link').textContent=L().cv+' ↗';document.getElementById('cv-link').href='cv.html?lang='+lang;document.getElementById('navigation').innerHTML=routes.filter(r=>!['conferences','recognition'].includes(r)).map(r=>`<a href="#${r}">${L()[r]}</a>`).join('');document.getElementById('navigation').setAttribute('aria-label',lang==='en'?'Main navigation':'Navegación principal');document.title=p.name+' · '+(isCV?L().cv:lang==='en'?'Academic profile':'Perfil académico');document.querySelector('meta[name="description"]').content=txt(p.introduction);view.className=isCV?'cv-view':'continuous-view';view.innerHTML=(isCV?`<div class="print-actions">${link('index.html?lang='+lang,'← '+L().back)}<button class="print-button" id="print-cv">${L().print}</button></div>`:'')+routes.map((r,i)=>`<section id="${r}" class="page-section section-tone-${i%2}" tabindex="-1">${photo(r)}${renderers[r]()}</section>`).join('');decorate();window.destroySectionObserver=initSectionObserver();let topLink=document.getElementById('back-top');if(!topLink){topLink=document.createElement('a');topLink.id='back-top';topLink.href='#about';topLink.className='back-top';document.body.append(topLink);}topLink.textContent=lang==='en'?'↑ Back to top':'↑ Volver arriba';if(!isCV)window.destroyGallery=initGallery(document.getElementById('research-gallery'),lang);document.getElementById('print-cv')?.addEventListener('click',()=>window.print());activate(active);}
const menu=document.getElementById('menu-toggle'),nav=document.getElementById('navigation');
function closeMenu(){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');}
menu.addEventListener('click',()=>menu.setAttribute('aria-expanded',String(nav.classList.toggle('open'))));
document.getElementById('language').addEventListener('change',e=>{const keep=active;lang=e.target.value;publicationPage=0;const u=new URL(location.href);u.searchParams.set('lang',lang);u.hash=keep;history.replaceState(null,'',u);render();jump(keep,false);});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open')){closeMenu();menu.focus();}});
document.addEventListener('click',e=>{const pageButton=e.target.closest('[data-publication-page]');if(pageButton){publicationPage=Number(pageButton.dataset.publicationPage);render();jump('publications',false);document.querySelector('.list-heading')?.focus?.({preventScroll:true});return;}const a=e.target.closest('a[href^="#"]');if(!a||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;const id=a.getAttribute('href').slice(1);if(!routes.includes(id))return;e.preventDefault();history.pushState(null,'','#'+id);closeMenu();jump(id);document.getElementById(id).focus({preventScroll:true});});
window.addEventListener('hashchange',()=>jump(routeFromHash(),false));
window.addEventListener('popstate',()=>jump(routeFromHash(),false));
window.addEventListener('scroll',()=>{if(scrollPending)return;scrollPending=true;requestAnimationFrame(()=>{const edge=(innerWidth<=650?document.querySelector('header').getBoundingClientRect().height:nav.getBoundingClientRect().height)+36;let current='about';for(const id of routes){if(document.getElementById(id).getBoundingClientRect().top<=edge)current=id;}if(innerHeight+scrollY>=document.documentElement.scrollHeight-5)current=routes[routes.length-1];activate(current);scrollPending=false;});},{passive:true});
active=routeFromHash();render();requestAnimationFrame(()=>{if(location.hash)jump(active,false);});
